name: Windows

on:
  push:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest

    env:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ZeroTier
        run: |
          $url = "https://install.zerotier.com/"
          Invoke-WebRequest -Uri $url -OutFile zerotier-install.ps1
          Get-Content zerotier-install.ps1 | Set-Content -NoNewline -Path zerotier-install-updated.ps1
          .\zerotier-install-updated.ps1

      - name: Join ZeroTier network
        run: |
          $env:PATH += ";C:\Program Files\ZeroTier\"
          zerotier-cli join $ZEROTIER_NETWORK_ID

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path WinRM/Client/Allowunencrypted -Value $true
          Set-ItemProperty -Path WinRM/Client/creativesession -Value $true
          Add-WindowsFeature -Name Remote-Desktop

      - name: Configure firewall
        run: |
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP user
        run: |
          New-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Get RDP endpoint
        id: get-rdp-endpoint
        run: |
          $endpoint = (zerotier-cli view $ZEROTIER_NETWORK_ID | Select-Object -ExpandProperty Members | Where-Object { $_.ID -eq "$ZEROTIER_NETWORK_ID" }).Members | Where-Object { $_.Type -eq "ip" } | Select-Object -ExpandProperty Addresses | Select-Object -First 1
          Write-Output "RDP endpoint: $endpoint"

      - name: Display RDP connection details
        run: |
          Write-Output "RDP endpoint: $endpoint"
          Write-Output "Username: runneradmin"
          Write-Output "Password: P@ssw0rd!"
