name: Windows RDP

on:
  push:
    branches:
      - main

jobs:
  windows-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install RDP server dependencies
        run: |
          Find-Module ServerManager
          Install-Module -Name ServerManager -RequiredVersion 12.0 -Scope CurrentUser

      - name: Configure RDP server
        run: |
          Import-Module ServerManager

          Add-WindowsFeature -Name Remote-Desktop

          Set-ItemProperty -Path WinRM/Client/Allowunencrypted -Value $true
          Set-ItemProperty -Path WinRM/Client/creativesession -Value $true

      - name: Start RDP server
        run: |
          Start-Service WinRM

          New-PSSession -ComputerName ${{ runner.ipAddress }}
          Enter-PSSession -ComputerName ${{ runner.ipAddress }}
